export const API_URLS = {
    BASE: 'https://camp-courses.api.kreosoft.space/',
    LOGIN: 'login',
    REGISTRATION: 'registration',
    PROFILE: 'profile',
    ROLES: 'roles',
    LOGOUT: 'logout',
    GROUPS: 'groups',
    USERS: 'users',
    MY_COURSES: 'courses/my',
    TEACHING_COURSES: '/courses/teaching',
    COURSE: 'courses/',
    COURSE_DETAILS: '/details',
    COURSE_STATUS: '/status',
    COURSE_NOTIFICATIONS: '/notifications',
}